### ISSUE TITLE
The Sample code throws a NPE

### ISSUE THREAD

**Issue by abhibang** [webfolderio/cdp4j#1]
Wanted to use this API for evaluating JS Coverage option available in the latest Chrome devtools, was more interested in the sample code related to the Profiler, but none the less below sample code snippet  
`
public class HelloWorld {

    public static void main(String[] args) {
        SessionFactory factory = new Launcher().launch();

        try (Session session = factory.create()) {
            session.navigate("https://webfolder.io");
            session.waitDocumentReady();
            String content = (String) session.getProperty("//body", "outerText");
            System.out.println(content);
        }

        factory.close();
    }
}`

throws an NPE:
`Exception in thread "main" java.lang.NullPointerException
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at io.webfolder.cdp.Launcher.launch(Launcher.java:122)
	at io.webfolder.cdp.Launcher.launch(Launcher.java:95)
	at HelloWorld.main(HelloWorld.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)`

Please let me know if anything I'm doing is wrong. Also as mentioned I would love to hear back from you on the Profiler sample code with the JS Coverage collection.

**Comment by webfolderio** [comment]
Hi,

Launcher.java cant not find chrome.exe. I will improve the Launcher.java and throw meaningful Exception rather than NullPointerException.

1) What is your OS? cdp4j tested only with Windows & Linux (Debian, RHEL).
2) What is your chrome installation directory?

Workaround solution:
Its not mandatory to launch Chrome with Launcher.java. You could start the Chrome manually and try to run above sample snippet.

```java
public static void main(String[] args) {
    SessionFactory factory = new SessionFactory();

    try (Session session = factory.create()) {
        session.navigate("https://webfolder.io");
        session.waitDocumentReady();
        String content = (String) session.getProperty("//body", "outerText");
        System.out.println(content);
    }

    factory.close();
}```

**Comment by webfolderio** [comment]
I added simple [Code Coverage](https://github.com/webfolderio/cdp4j/blob/master/src/test/java/io/webfolder/cdp/sample/CodeCoverage.java) sample.
