### ISSUE TITLE
Why I get different boxModel?

### ISSUE THREAD

**Issue by tylr2017** [webfolderio/cdp4j#100]
When I get the root node's Boxmodel, I execute the code twice, but the resulting Boxmodel is different. Why? My code is as follows:
<img width="1121" alt="default" src="https://user-images.githubusercontent.com/33024821/41340664-71aeac02-6ee7-11e8-9214-7e82dc942454.png">

My implementation results are as follows:
<img width="1353" alt="default" src="https://user-images.githubusercontent.com/33024821/41340770-a8d9acf4-6ee7-11e8-9c50-fee5b3eb2dd9.png">

Thank you very much!

**Comment by webfolderio** [comment]
Hi @tylr2017 

Could you please test your code with lastest version: https://oss.sonatype.org/content/repositories/snapshots/io/webfolder/cdp4j/3.0.1-SNAPSHOT/cdp4j-3.0.1-20180610.140020-2.jar
