### ISSUE TITLE
Can cdp4j connect to existing headless(or not) chrome?  or it always starts a new chrome instance?

### ISSUE THREAD

**Issue by simon998yang** [webfolderio/cdp4j#101]
I need to handle concurrent requests , and it's slow to launch then kill chrome for each request.

**Comment by webfolderio** [comment]
Yes, cdp4j supports concurrent requests.

There are two ways to implement concurrent requests.
* Launch a new chrome process for each session.
* Launch a single chrome process and create incognito/private context for each session.

Here is a sample for incognito mode:
https://github.com/webfolderio/cdp4j/blob/master/src/test/java/io/webfolder/cdp/sample/IncognitoBrowsing.java

You should better to use incognito mode for your use case.

**Comment by simon998yang** [comment]
Thanks for the response. How can I launch or connect to chrome in a remote host?

**Comment by webfolderio** [comment]
`SessionFactory factory = new SessionFactory("127.0.0.1", 9222);`
