### ISSUE TITLE
Passing arguments to printtopdf is not working

### ISSUE THREAD

**Issue by santhoshmanikandan** [webfolderio/cdp4j#12]
Hi
I tried passing arguments to printToPDF function. But it is not taking the values passed to it. Getting the same pdf as th printToPDF function with no arguments.
Have attached my code snippet and the output pdf
![image](https://user-images.githubusercontent.com/7881020/27898052-9d2bbe8c-6241-11e7-8bff-e459f971fd11.png)
[webfolder-linux-setup475936408639400582.pdf](https://github.com/webfolderio/cdp4j/files/1126886/webfolder-linux-setup475936408639400582.pdf)

**Comment by webfolderio** [comment]
Hi @santhoshmanikandan 

You could enable debug logs. When you will turn on debug logging, you will see all parameters that will passed to chrome.

`logback.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration packagingData="true">

    <statusListener class="ch.qos.logback.core.status.NopStatusListener" />

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <Pattern>%d{HH:mm:ss.SSS} [%-10thread] %-5level %msg%n</Pattern>
        </layout>
    </appender>

    <logger name="cdp4j.session"     level="DEBUG" />
    <logger name="cdp4j.flow"        level="DEBUG" />
    <logger name="cdp4j.factory"     level="DEBUG" />
    <logger name="cdp4j.ws.request"  level="DEBUG" />
    <logger name="cdp4j.ws.response" level="DEBUG" />

    <root level="debug">
        <appender-ref ref="STDOUT" />
    </root>

</configuration>
```

`sample output`
```text
12:16:31.297 [cpd4j-1   ] DEBUG {"id":22,"result":{"root":{"nodeId":48,"backendNodeId":2,"nodeType":9,"nodeName":"#document","localName":"","nodeValue":"","childNodeCount":1,"children":[{"nodeId":49,"parentId":48,"backendNodeId":3,"nodeType":1,"nodeName":"HTML","localName":"html","nodeValue":"","childNodeCount":2,"children":[{"nodeId":50,"parentId":49,"backendNodeId":4,"nodeType":1,"nodeName":"HEAD","localName":"head","nodeValue":"","childNodeCount":0,"children":[{"nodeId":51,"parentId":50,"backendNodeId":5,"nodeType":3,"nodeName":"#text","localName":"","nodeValue":"\n"}],"attributes":[]},{"nodeId":52,"parentId":49,"backendNodeId":6,"nodeType":1,"nodeName":"BODY","localName":"body","nodeValue":"","childNodeCount":6,"attributes":[]}],"attributes":[],"frameId":"8464.1"}],"documentURL":"file:///C:/projects/cdp4j/target/test-classes/checkbox.html","baseURL":"file:///C:/projects/cdp4j/target/test-classes/checkbox.html","xmlVersion":""}}}
```

**Comment by santhoshmanikandan** [comment]
Hi thanks for the reply enabled it. But when I tried now getting a different error
16:48:59.253 [main] DEBUG cdp4j.ws.request - {"method":"Target.createBrowserContext","params":{},"id":1}
16:48:59.260 [cpd4j-1] DEBUG cdp4j.ws.response - {"id":1,"result":{"browserContextId":"08c776c1-6c8e-4070-b28f-6805c0549adc"}}
16:48:59.263 [main] DEBUG cdp4j.ws.request - {"method":"Target.createTarget","params":{"arg3":"08c776c1-6c8e-4070-b28f-6805c0549adc","arg2":768,"arg1":1366,"arg0":"about:blank"},"id":2}
16:48:59.264 [cpd4j-1] DEBUG cdp4j.ws.response - {"error":{"code":-32602,"message":"Missing or invalid 'url' parameter"},"id":2}
16:48:59.270 [main] DEBUG cdp4j.ws.request - {"method":"Target.disposeBrowserContext","params":{"arg0":"08c776c1-6c8e-4070-b28f-6805c0549adc"},"id":3}
Exception in thread "main" io.webfolder.cdp.exception.CommandException: Missing or invalid 'url' parameter
	at io.webfolder.cdp.session.WSAdapter.lambda$0(WSAdapter.java:126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Just ran the example java inside the project provided by you. 

![image](https://user-images.githubusercontent.com/7881020/27908894-ad252010-626b-11e7-8766-4d8de86e3217.png)

**Comment by webfolderio** [comment]
As i see from the logs, method paramater names are not stored (arg0, arg1).  If you use cdp4j __from source__ you should enable "Store information about method parameters" for Eclipse.

![eclipse-param-names](https://user-images.githubusercontent.com/23472649/27909913-8aa3c5d8-625b-11e7-9948-1b90123d6bdd.png)

**Comment by santhoshmanikandan** [comment]
Hi 
 Have attached the output printed in console. Seems like arguments are getting passed correctly. 
13:06:33.040 [main] DEBUG cdp4j.ws.request - {"method":"Page.printToPDF","params":{"marginRight":0.4,"pageRanges":"","paperWidth":8.5,"displayHeaderFooter":false,"scale":1.0,"marginBottom":0.4,"printBackground":false,"landscape":true,"paperHeight":11.0,"marginTop":0.4,"marginLeft":0.4},"id":7}
[output.txt](https://github.com/webfolderio/cdp4j/files/1130326/output.txt)
