### ISSUE TITLE
Version 4.2.2 is not yet available on Maven Central Repository.

### ISSUE THREAD

**Issue by LeMoussel** [webfolderio/cdp4j#125]
The latest version (4.2.2) is not yet available on Maven Central Repository (https://mvnrepository.com/artifact/io.webfolder/cdp4j).

It would be great to have the latest changes available via maven dependency.

**Comment by webfolderio** [comment]
Hi,

We deploy the latest artifacts to GitHub package.

https://github.com/webfolderio/cdp4j/packages/29482

**Comment by LeMoussel** [comment]
OKAY. Thank you.

**Comment by LeMoussel** [comment]
As described,  Add to pom.xml:
``` xml
<dependency>
  <groupId>io.webfolder</groupId>
  <artifactId>cdp4j</artifactId>
  <version>4.2.2</version>
</dependency>
```

Do `mvn install`

Got this error:
`
[ERROR] Failed to execute goal on project Coweb: Could not resolve dependencies for project com.coweb:Coweb:jar:1.0-SNAPSHOT: Failure to find 
io.webfolder:cdp4j:jar:4.2.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
`

**Comment by sunny4381** [comment]
@LeMoussel Follow below instructions to use GitHub Package with Maven.

https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages

and then you'll be fine.
