### ISSUE TITLE
How to get only 'ResourceType.Document' for the requested Url?

### ISSUE THREAD

**Issue by LeMoussel** [webfolderio/cdp4j#126]
With this 
``` java
      session.addEventListener((e, d) -> {
        // https://github.com/webfolderio/cdp4j/blob/master/src/main/java/io/webfolder/cdp/event/Events.java
        if (NetworkResponseReceived.equals(e)) {
          ResponseReceived rr = (ResponseReceived) d;
          ResourceType type = rr.getType();

          if (ResourceType.Document.equals(type)) {
            Response response = rr.getResponse();

            int statusCode = response.getStatus().intValue();
            String reason = response.getStatusText();
            String url = response.getUrl();

            System.out.println(url + " HTTP StatusCode: " + statusCode + " (" + reason + ")");
          }
        }
      });
```
When I make a request to http://f4b1.com/ like this 
```  java
      session.navigate("http://f4b1.com/");
      session.waitDocumentReady(60 * 1000);
```

I got multiple `NetworkResponseReceived` and therefore three `ResourceType.Document`: 
> http://f4b1.com/ HTTP StatusCode: 200 (OK)
> https://googleads.g.doubleclick.net/pagead/html/r20200324/r20190131/zrt_lookup.html HTTP StatusCode: 200 ()
> https://googleads.g.doubleclick.net/pagead/ads?client=..... HTTP StatusCode: 200 ()  

Is it possible to get only `ResourceType.Document` for the requested Url?

**Comment by webfolderio** [comment]
Sorry for late reply. Events produced by Google chrome and there is no way to limit produced events.
