### ISSUE TITLE
memory leak of seesion.matches

### ISSUE THREAD

**Issue by upccup** [webfolderio/cdp4j#136]
![image](https://user-images.githubusercontent.com/13341880/92063077-d3c16680-edcc-11ea-9af0-91aac69e977f.png)

![image](https://user-images.githubusercontent.com/13341880/92063420-a923dd80-edcd-11ea-9b72-f981d886d1b8.png)

this is the call tree and memory status.  seesion.matches create much com.google.gson.internal.LinkedTreeMap$Node object
and not recycle by garbage collection

**Comment by webfolderio** [comment]
What is your cdp4j version?

**Comment by upccup** [comment]
> What is your cdp4j version?

 <cdp4j.version>4.2.2</cdp4j.version>

**Comment by webfolderio** [comment]
This might be occured if and only if Session and SessionFactory is not closed. Is this memory snapshot captured after sessionfactory.close() & session.close(). If the answer yes, this is a major bug.

**Comment by upccup** [comment]
> This might be occured if and only if Session and SessionFactory is not closed. Is this memory snapshot captured after sessionfactory.close() & session.close(). If the answer yes, this is a major bug.

thinks for reply. i will check my code and try again.

thinks again.

**Comment by upccup** [comment]
> This might be occured if and only if Session and SessionFactory is not closed. Is this memory snapshot captured after sessionfactory.close() & session.close(). If the answer yes, this is a major bug.

I have been check code and close the seesion with try-with-reource but the memory is still happen 

this is the code
```
    public void runConsumer(Consumer<Session> consumer, Options options) {
        Launcher launcher = new Launcher(options);

        try(SessionFactory factory = launcher.launch(); Session session = factory.create()) {
            CDPContextHolder.bind(session, factory);

            // session.enableNetworkLog();
            // session.enableConsoleLog();
            session.setUserAgent(xingtuBizConfig.getUserAgent());

            consumer.accept(session);

        } catch (Exception e) {
            log.error("Caught exception during process spider", e);
        } finally {
            launcher.kill();
        }
    }
```

**Comment by upccup** [comment]
this question not recurrent after close every seesion make sure closed! thx again
