### ISSUE TITLE
No way to shutdown the chrome process programatically

### ISSUE THREAD

**Issue by cpuchakayaka** [webfolderio/cdp4j#14]
The Launcher class thats launches the chrome process doesn't have way method shutdown the chrome process.

**Comment by cpuchakayaka** [comment]
what is the timeline of 1.2.0 milestone, i can contribute as i need this quickly :)

**Comment by webfolderio** [comment]
Hi @cpuchakayaka 

I don't know the exact date for the 1.2 because i couldn't find a way to kill chrome programmatically. I could kill the process by pid/processId but chrome creates a new process for each tab. Somehow i should group process created by chrome and kill all process in that group. Another solution using [single-process](https://www.chromium.org/developers/design-documents/process-models) mode of chrome. Unfortunately i try single-process mode on windows but it did not work as expected.

**Comment by cpuchakayaka** [comment]
I am actually in the process of implementing this in my code using **pkill** and trying to find the parent chrome process using **remote-debugging-port**

In my code i launched multiple tabs when i run the command **ps -ef | grep chome** i get this output
C02P990JG3QD:Versions cpuchakayala$ ps -ef | grep chrome
215168532 55951     1   0  3:28PM ??         0:00.88 /Applications/chrome_canary.app/Contents/MacOS/chrome_canary --remote-debugging-port=9000 --user-data-dir=/var/folders/jl/9lc56p911v33p3vwxmqr1s786d6dhm/T/remote-profile --disable-translate --disable-extensions --no-default-browser-check --disable-plugin-power-saver --disable-sync --no-first-run --safebrowsing-disable-auto-update --disable-popup-blocking --headless
215168532 55953     1   0  3:28PM ??         0:00.01 /Applications/chrome_canary.app/Contents/Versions/61.0.3145.0/Google Chrome Framework.framework/Helpers/crashpad_handler --monitor-self-annotation=ptype=crashpad-handler --database=/Applications/chrome_canary.app/Contents/Versions/61.0.3145.0/Google Chrome Framework.framework --url=https://clients2.google.com/cr/report --annotation=channel=canary --annotation=plat=OS X --annotation=prod=Chrome_Mac --annotation=ver=61.0.3145.0 --handshake-fd=8
215168532 55954 55951   0  3:28PM ??         0:02.45 /Applications/chrome_canary.app/Contents/MacOS/chrome_canary --type=gpu-process --headless --headless --use-gl=any --supports-dual-gpus=false --gpu-vendor-id=0xffff --gpu-device-id=0xffff --gpu-driver-vendor=osmesa --gpu-driver-version --gpu-driver-date --headless --service-request-channel-token=42164DE467793E1545B5E5929522506C
215168532 55955 55951   0  3:28PM ??         0:00.08 /Applications/chrome_canary.app/Contents/MacOS/chrome_canary --type=renderer --use-gl=any --service-pipe-token=B90CE1920365DE89FCE6438D1FF402CC --lang=en-US --headless --enable-pinch --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,34037;0,12,34037;0,13,34037;0,14,3553;0,15,3553;0,16,3553;0,17,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,34037;1,12,34037;1,13,34037;1,14,3553;1,15,3553;1,16,3553;1,17,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,34037;2,12,34037;2,13,34037;2,14,3553;2,15,3553;2,16,3553;2,17,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,34037;3,14,34037;3,15,3553;3,16,34037;3,17,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,34037;4,14,34037;4,15,3553;4,16,34037;4,17,34037 --service-request-channel-token=B90CE1920365DE89FCE6438D1FF402CC --renderer-client-id=3
215168532 56067 55951   0  3:31PM ??         0:00.63 /Applications/chrome_canary.app/Contents/MacOS/chrome_canary --type=renderer --use-gl=any --service-pipe-token=646E829EE411345D2790C5864C24454D --lang=en-US --headless --enable-pinch --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,34037;0,12,34037;0,13,34037;0,14,3553;0,15,3553;0,16,3553;0,17,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,34037;1,12,34037;1,13,34037;1,14,3553;1,15,3553;1,16,3553;1,17,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,34037;2,12,34037;2,13,34037;2,14,3553;2,15,3553;2,16,3553;2,17,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,34037;3,14,34037;3,15,3553;3,16,34037;3,17,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,34037;4,14,34037;4,15,3553;4,16,34037;4,17,34037 --service-request-channel-token=646E829EE411345D2790C5864C24454D --renderer-client-id=8
215168532 56068 55951   0  3:31PM ??         0:00.07 /Applications/chrome_canary.app/Contents/MacOS/chrome_canary --type=renderer --use-gl=any --service-pipe-token=929C4C2393095C41B771CB92973741C1 --lang=en-US --headless --enable-pinch --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,34037;0,12,34037;0,13,34037;0,14,3553;0,15,3553;0,16,3553;0,17,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,34037;1,12,34037;1,13,34037;1,14,3553;1,15,3553;1,16,3553;1,17,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,34037;2,12,34037;2,13,34037;2,14,3553;2,15,3553;2,16,3553;2,17,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,34037;3,14,34037;3,15,3553;3,16,34037;3,17,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,34037;4,14,34037;4,15,3553;4,16,34037;4,17,34037 --service-request-channel-token=929C4C2393095C41B771CB92973741C1 --renderer-client-id=9
215168532 56086 55951   0  3:31PM ??         0:00.53 /Applications/chrome_canary.app/Contents/MacOS/chrome_canary --type=renderer --use-gl=any --service-pipe-token=89B43E1811ADA8695A22C30CC1EBED63 --lang=en-US --headless --enable-pinch --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,34037;0,12,34037;0,13,34037;0,14,3553;0,15,3553;0,16,3553;0,17,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,34037;1,12,34037;1,13,34037;1,14,3553;1,15,3553;1,16,3553;1,17,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,34037;2,12,34037;2,13,34037;2,14,3553;2,15,3553;2,16,3553;2,17,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,34037;3,14,34037;3,15,3553;3,16,34037;3,17,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,34037;4,14,34037;4,15,3553;4,16,34037;4,17,34037 --service-request-channel-token=89B43E1811ADA8695A22C30CC1EBED63 --renderer-client-id=10
215168532 56087 55951   0  3:31PM ??         0:00.08 /Applications/chrome_canary.app/Contents/MacOS/chrome_canary --type=renderer --use-gl=any --service-pipe-token=815B9A239C8F04E2DD17D8C5A9270FA6 --lang=en-US --headless --enable-pinch --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,34037;0,12,34037;0,13,34037;0,14,3553;0,15,3553;0,16,3553;0,17,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,34037;1,12,34037;1,13,34037;1,14,3553;1,15,3553;1,16,3553;1,17,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,34037;2,12,34037;2,13,34037;2,14,3553;2,15,3553;2,16,3553;2,17,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,34037;3,14,34037;3,15,3553;3,16,34037;3,17,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,34037;4,14,34037;4,15,3553;4,16,34037;4,17,34037 --service-request-channel-token=815B9A239C8F04E2DD17D8C5A9270FA6 --renderer-client-id=11
215168532 56110  6630   0  3:34PM ttys015    0:00.00 grep chrome

All the process with name **--renderer-client-id** are the tabs and they all have one common parent other than crash pad handler, i can kill main chrome process which would kill subprocess

The command i am thinking of is **pkill -f 'remote-debugging-port=9000'**

The test I did is on MacOS, hoping it would be similar behavior in windows

**Comment by webfolderio** [comment]
Thanks, thats a good idea. I am going to test your suggestion on Windows & Linux platform.

**Comment by derekst991** [comment]
I need this feature too so I have hacked it into my local copy by modifying the Launcher class.  When you start the Chrome process using Runtime.exec(...), you get back a Process object that you can use to shut it down later if you hang on to a reference to it.  Just call process.destroy().

[Launcher.java.zip](https://github.com/webfolderio/cdp4j/files/1234321/Launcher.java.zip)

**Comment by webfolderio** [comment]
Fixed: https://github.com/webfolderio/cdp4j/blob/master/src/main/java/io/webfolder/cdp/ProcessManager.java

**Comment by loveship00** [comment]
i can't shutdown chrome process on linux via ProcessManager
