### ISSUE TITLE
Issues with xpath

### ISSUE THREAD

**Issue by nhrdl** [webfolderio/cdp4j#15]
First, great library and coding style. Very clear and understandable code.

Lot of methods that accept xpath are failing. The docs say I can pass CSS selector or XPATH selector. However passing XPATH fails.  I traced the problem to 
io.webfolder.cdp.session.Selector.getNodeId(String, Object...) method.

Around line 329 where existence of sizzle is checked, xpath check is not performed as it's done in getObjectId function in the same class. Applying this check makes focus method work with xpath.

Since I am not sure the impact, not submitting the patch.

**Comment by webfolderio** [comment]
Hi @nhrdl 

Thanks for the suggestion & bug report.

There is only one [test case](https://github.com/webfolderio/cdp4j/blob/master/src/test/java/io/webfolder/cdp/test/TestSession.java#L158) for the xpath selector. I will add more test for the xpath selector.

**Comment by agilecreativity** [comment]
@webfolderio 

I can confirm the same issue when using xpath. 
Even for simple xpath like "//p" is failing for the same reason.

**Comment by agilecreativity** [comment]
@nhrdl 

What is your workaround that you make it work?

**Comment by nhrdl** [comment]
@agilecreativity , details are in the bug description. I ended up modifying the Selector.getNodeId code locally. It then works fine.

**Comment by agilecreativity** [comment]
@nhrdl 
Could you share what you changed I still don't get what is in the bug description?
Thanks

**Comment by nhrdl** [comment]
interface io.webfolder.cdp.session.Selector,, function 
io.webfolder.cdp.session.Selector.getObjectId(String, Object...) on or 
around line 259 when I cloned the repository.

First line is checking something like following

final boolean sizzle = getThis().useSizzle();

Please add following line after the check

final boolean xpath = selector.charAt(0) == '/';

and modify next if statement where it checks for sizzle like follows

if (sizzle || xpath) {

**Comment by agilecreativity** [comment]
Thanks @nhrdl 

I still get the errors with your suggestion when trying to use xpath.
I use very simple xpath just to see if this will work.

There might be more than this fix needed to make `xpath` work properly.
Thanks again for sharing.
