### ISSUE TITLE
Request to update documentation

### ISSUE THREAD

**Issue by nhrdl** [webfolderio/cdp4j#16]
For those who are new to project and using source code than pre compiled released jar, you need to make sure "Store Information about method parameters" flag for reflection is set to true. Otherwise in tools such as eclipse, after importing maven project, no sample application works as by default (at least in my installation), this flag is not checked.

Please add to  the documentation following information

1. Compiler flags for using reflection
2. How to enable logging especially if you are using other library such as log4j

**Comment by webfolderio** [comment]
hi @nhrdl 

Thanks for suggestion. I will improve the documentation.
