### ISSUE TITLE
Keep running into the error " No data found for resource with given identifier"

### ISSUE THREAD

**Issue by cpuchakayaka** [webfolderio/cdp4j#17]
Keep running into the error "**No data found for resource with given identifier**"

Stacktrace

Exception in thread "cpd4j-2" io.webfolder.cdp.exception.CommandException: No data found for resource with given identifier
https://fonts.googleapis.com/css?family=Roboto:300,400,500|Material+Icons
	at io.webfolder.cdp.session.WSAdapter.lambda$0(WSAdapter.java:126)
	at io.webfolder.cdp.session.WSAdapter$$Lambda$2/1628514283.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by webfolderio** [comment]
Hi @cpuchakayaka 

"__No data found for resource with given identifier__" thrown by chrome. This occur when the [response body is empty](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/inspector/InspectorResourceAgent.cpp#962).

Please send a simple test case to produce error so that i could help more.

**Comment by cpuchakayaka** [comment]
Hello here is my test code, I am running MacOS

public class CDPTester
{

    public static void main(String[] args) {

        Launcher launcher = new Launcher();

        try (SessionFactory factory = launcher.launch("/Applications/chrome_canary.app/Contents/MacOS/chrome_canary", asList("--headless", "--disable-gpu"))) {
            String firstContext = factory.createBrowserContext();

            try (Session session = factory.create(firstContext)) {
                AtomicInteger requestCount = new AtomicInteger(0);
                AtomicInteger responseCount =  new AtomicInteger(0);
                session.getCommand().getNetwork().enable();
                session.getCommand().getPage().enable();
                session.getCommand().getDOM().enable();
                session.navigate("http://goo.gl");
                session.addEventListener((e, d) -> {
                    if (NetworkResponseReceived.equals(e)) {
                        ResponseReceived rr = (ResponseReceived) d;
                        Response response = rr.getResponse();
                        GetResponseBodyResult rb = session.getCommand().getNetwork().getResponseBody(rr.getRequestId());
                        String body = rb.getBody();
                        //System.out.println("----------------------------------------");
                        //System.out.println("URL       : " + response.getUrl());
                        //System.out.println("Status    : HTTP " + response.getStatus().intValue() + " " + response.getStatusText());
                        //System.out.println("Mime Type : " + response.getMimeType());
                       // System.out.println("Content   : " + body.substring(0, body.length() > 1024 ? 1024 : body.length()));
                        responseCount.incrementAndGet();
                    }

                    if (NetworkRequestWillBeSent.equals(e)) {
                        RequestWillBeSent rr = (RequestWillBeSent) d;
                        if(rr.getRedirectResponse() != null) {
                            System.out.println(rr.getRequest().getUrl());
                            System.out.println("Redirected response " + rr.getRequestId());
                            System.out.println("----------------------------------------");
                            System.out.println("URL       : " + rr.getRedirectResponse().getUrl());
                            System.out.println("Status    : HTTP " + rr.getRedirectResponse().getStatus().intValue() + " " + rr.getRedirectResponse().getStatusText());
                            System.out.println("Mime Type : " + rr.getRedirectResponse().getMimeType());
                        }
                        requestCount.incrementAndGet();
                    }

                    if(NetworkRequestServedFromCache.equals(e)) {
                        RequestServedFromCache rr = (RequestServedFromCache) d;
                        System.out.println("Cache" + rr.getRequestId());
                        responseCount.incrementAndGet();

                    }

                    if(NetworkLoadingFailed.equals(e)) {
                        LoadingFailed rr = (LoadingFailed) d;
                        System.out.println("Failed" + rr.getRequestId());
                        responseCount.incrementAndGet();

                    }


                });
                session.waitDocumentReady();
                session.wait(10000);
                List<Node> flattenedDocument = session.getCommand().getDOM().getFlattenedDocument();
                Node document = session.getCommand().getDOM().getDocument();
                Node contentDocument = document.getContentDocument();
                System.out.println(document.getValue());
                String content = (String) session.getProperty("//body", "outerText");
                System.out.println("---------------------------------------- DOM DOM DOM ------------------------------");
                System.out.println(content);

                System.out.println("Request Count " + requestCount.get() + " Response Count " + responseCount.get());
                session.close();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
