### ISSUE TITLE
Headless Chrome screenshots sometimes return null

### ISSUE THREAD

**Issue by moghtader** [webfolderio/cdp4j#18]
Hi there,

I am trying to take screenshots with Headless Chrome on MacOS. Every few session screenshot capture attempts, one of them will return with null with no exception given.

Some findings on my system:
- Reproducible on both Stable Chrome and Canary Chrome
- This issue does not happen on non-headless Chrome with Session.create()
- Closing and reopening sessions between screenshots does not appear to help
- Using getPage() does not appear to fix the issue either

Let me if you need more information or how I can help!
Jake

**Comment by webfolderio** [comment]
Hi @moghtader 

Did you call the [activate()](https://github.com/webfolderio/cdp4j/blob/master/src/test/java/io/webfolder/cdp/sample/Screenshot.java#L50) method the frame/tab before taking the screenshot?

**Comment by moghtader** [comment]
Unfortunately, activate() does not seem to solve the problem either. I'm going to run the same code on a linux box in a few hours to isolate if it is a macOS issue.

**Comment by moghtader** [comment]
Hi @webfolderio 

It seems to be a bug with Chrome 60 for Mac OS X... It doesn't appear to happen on CentOS... Sorry for the confusion!

Thanks,
Jake

**Comment by webfolderio** [comment]
I am glad that your problem has been resolved.
