### ISSUE TITLE
Feature request - reconnect to the browser if devtools window is opened

### ISSUE THREAD

**Issue by nhrdl** [webfolderio/cdp4j#19]
In class WSAdapater, if "Inspector.detached" event is fired, browser window is immediately closed. This event can happen if user opens devtools window in chrome for some reason.

Is it possible to handle this in same way chrome driver does. It tries to reconnect to devtools in case if it gets disconnected. You can see this by running selenium/chrome driver combo and opening devtools window. As soon as any selenium command is executed, devtools window is closed again.

**Comment by webfolderio** [comment]
Thanks for the suggestion. It might be good to add reconnect feature to SessionFactory.

**Comment by webfolderio** [comment]
Duplicate issue, #35
