### ISSUE TITLE
Headless: Session.close() does not actually close the target

### ISSUE THREAD

**Issue by ka-arg** [webfolderio/cdp4j#2]
This applies to version 1.0.2.

In headless mode, when creating additional sessions via SessionFactory's createBrowserContext() and create(browserContextId); the connected flag on session is set prior to issuing sessionFactory.close(...). 

So 
<pre>
headlessSession.getCommand().getTarget().closeTarget(targetId);
</pre>
will never be called.

**Comment by webfolderio** [comment]
Hi @ka-arg 

Thanks for the bug report.
The order is incorrect. I fixed it.
