### ISSUE TITLE
Feature request - allow user to set chrome user-data-dir option

### ISSUE THREAD

**Issue by nhrdl** [webfolderio/cdp4j#20]
I have a requirement where I need to setup chrome profile in certain way. Even though method io.webfolder.cdp.Launcher.launch(String, List<String>) allows other chrome parameters to be set, it gets the remoteProfileData on it's own.

Please allow to set the chrome profile directory.

I can submit a pull request for you if you want me to make code change and you can apply it after reviewing code.

**Comment by webfolderio** [comment]
Hi @nhrdl 

Thanks for the suggestion. Its very bad decission not allow to use custom remote profile path. I am going to improve Launcher api to support custom remote path.

**Comment by cpuchakayaka** [comment]
It might be also good to provide a way to override the default chrome options set in the Launcher.launch() other than the merge thats happening now
