### ISSUE TITLE
Feature request - allow connection to existing chrome connection

### ISSUE THREAD

**Issue by nhrdl** [webfolderio/cdp4j#21]
Is it possible to establish session with known remote debugging port rather than creating new chrome instance?

Use case: I have lot of selenium based code and trying to use this library to enhance existing code to add support for what selenium does not support. For example I am interested in knowing when when my AJAX calls are finished and when DOM mutation is completed which selenium does not support directly.

In my experiments, this library supported that feature nicely and very easily. If we can connect to existing instance of chrome, my migration path will be lot easier.

**Comment by nhrdl** [comment]
May be I was wrong, it seems like session factory is already supporting port and host.

**Comment by webfolderio** [comment]
Hi @nhrdl 

>Is it possible to establish session with known remote debugging port rather than creating new chrome instance?

Yes you could connect to an existing chrome with custom remote debugging port. Just use SessionFactory class and pass the [port number](https://github.com/webfolderio/cdp4j/blob/master/src/main/java/io/webfolder/cdp/session/SessionFactory.java#L113).

>Use case: I have lot of selenium based code and trying to use this library to enhance existing code to add support for what selenium does not support. For example I am interested in knowing when when my AJAX calls are finished and when DOM mutation is completed which selenium does not support directly.

As far as i understood you are trying to connect chrome Simultaneously. Unfortunately chrome does not support [simultaneous clients](https://chromedevtools.github.io/devtools-protocol/#simultaneous). That means that you can not share same chrome instance with selenium & cdp4j.

**Comment by nhrdl** [comment]
I know chrome does not support simultaneous clients. However one approach that selenium chrome driver  takes is close any existing windows before establishing connections. For example if I open developer panel to inspect the element, CDP4J gets disconnected event. Current behavior is to close browser window. I am testing a patch where it does not close the browser window and a wrapper around session object that checks if session is connected and reconnects if needed.

**Comment by webfolderio** [comment]
Duplicate issue, #35
