### ISSUE TITLE
session.captureScreenshot() may be null

### ISSUE THREAD

**Issue by paine1690** [webfolderio/cdp4j#24]
The Chrome Devtools Protocol has changed a lot in [Emulation Domain](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/).

The method `forceViewport`has been removed and [`setVisibleSize` ](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setVisibleSize) has been Deprecated and dose nothing.
So the Screenshot sample will throw a NPE

**Comment by webfolderio** [comment]
Hi @paine1690 

I am going to update the api.
