### ISSUE TITLE
session.waitDocumentReady() not working in headless mode?

### ISSUE THREAD

**Issue by tole42** [webfolderio/cdp4j#26]
```java
public class App 
{
    public static void main( String[] args ) throws InterruptedException {
        Launcher launcher = new Launcher();
        try (SessionFactory factory = launcher.launch(Arrays.asList("--headless", "--disable-gpu"));
             Session session = factory.create()) {

          session.setUserAgent("My Browser");
          session.wait(500);
          session.getCommand().getDOM().enable();
          session.navigate("https://httpbin.org/headers");
          session.waitDocumentReady();
          session.wait(1000);
          String response = (String) session.evaluate("document.body.textContent");

          Gson gson = new Gson();
          Map json = gson.fromJson(response, Map.class);
          Map headers = (Map) json.get("headers");

          System.out.println(headers.get("User-Agent"));

        }
    }
}
```

Without 
`session.wait(1000);` response is empty

**Comment by webfolderio** [comment]
Hi @tole42 

`session.waitDocumentReady()` waits until `loadEventFired`. Unfoutunately this doesn't mean that DOM is ready to use and loaded. I should rename the method with meaningful name or should improve the logic.

[Other](https://github.com/cyrus-and/chrome-remote-interface/issues/184) libraries also listen `loadEventFired` event to wait the DOM. This is the only reasonable way to wait DOM with Chrome Remote Debugging Protocol.

You should add your own wait logic to detect if the page is loaded or not.

**Comment by nhrdl** [comment]
@tole42 
In my experience for scraping, load events are almost useless especially if site is using ajax calls to get the data. As webfolderio suggested, it's much better to have own logic like checking existence of element.

Another generic approach I am experimenting with this library is to listen for network and mutation events and continue one second after last event.
