### ISSUE TITLE
NullPointerException  when the program run first time

### ISSUE THREAD

**Issue by paine1690** [webfolderio/cdp4j#3]
in SessionFactory.java 

Target target = headlessSession.getCommand().getTarget();

it throws a java.lang.NullPointerException every time.
so anyone have the same problem?

**Comment by webfolderio** [comment]
Hi @paine1690 ,

Could you please send me a test case.

**Comment by paine1690** [comment]
`  public static void main(String[] args) throws Exception {


    SessionFactory factory = new Launcher().launch("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
        "--headless", "--disable-gpu");

    String  firstContext = factory.createBrowserContext();
    Session session = factory.create(firstContext).enableDetailLog().enableConsoleLog();
    session.getCommand().getNetwork().enable();
    session.navigate("http://www.baidu.com");
    session.setUserAgent("");
    
    session.addEventListener((e, d) -> {
      if (NetworkResponseReceived.equals(e)) {
          ResponseReceived rr = (ResponseReceived) d;
          Response response = rr.getResponse();
          GetResponseBodyResult rb = session.getCommand().getNetwork().getResponseBody(rr.getRequestId());
          if (response.getMimeType().contains("image")) {
            imageSaver.save(rb, response);
          }
      }
    });
    session.waitDocumentReady();
    factory.disposeBrowserContext(firstContext);
    factory.close();
  }`

I have tried again to find that when i run the program first time, it will throw a NullPointerException , and at the same time port 9222 is opened.  when i run the program again, it can work .

**Comment by paine1690** [comment]
@webfolderio   I have tried again to find the problem.
If I change the code : 
`      Mylauncher myLauncher = null;
      String firstContext ="";
      boolean flag = true;
      int i = 0;
      while (flag) {
        try {
          myLauncher = new Mylauncher(debugPort);
          factory = myLauncher.launch(chromePath, args);
          firstContext = factory.createBrowserContext();
          flag = false;
        } catch (Exception e) {
          System.out.println(i++);
          e.printStackTrace();
        }
        Thread.sleep(1000);
      }`

It will work well.
So maybe in the headless mode, the  factory.eadlessSession may be null in the first a few seconds.

**Comment by webfolderio** [comment]
> So maybe in the headless mode, the factory.eadlessSession may be null in the first a few seconds.
Yes, you are correct about this.
Launcher launch the chrome and returns immediately. SessionFactory will fail if chrome is not ready to run and WebSocket is not available.

I should add a wait logic to check if chrome is ready and WebSocket is available to connect.

**Comment by webfolderio** [comment]
Fixed and released 1.1.0
