### ISSUE TITLE
Constant.EMPTY_NODE_ID check

### ISSUE THREAD

**Issue by nhrdl** [webfolderio/cdp4j#30]
There are two places I have found so far that checks the equality with Constant.EMPTY_NODE_ID using == operator. This check fails chrome itself returns empty value or zero as shown in following log

> io.webfolder.cdp.logger.CdpSlf4jLogger.debug(CdpSlf4jLogger.java:46) - {"id":5,"result":{}}
> io.webfolder.cdp.logger.CdpSlf4jLogger.debug(CdpSlf4jLogger.java:46) - {"id":4,"result":{"nodeId":0}}

As a result method such as  io.webfolder.cdp.session.Mouse.click(String, Object...) fail. 

May be java.util.Objects.equals(Object, Object) might be better check for this

**Comment by webfolderio** [comment]
hi @nhrdl 

Thanks for the bug report.

I replaced `==` operator with `Object.equals()`.
