### ISSUE TITLE
How to use selector for multiple elements?

### ISSUE THREAD

**Issue by nhrdl** [webfolderio/cdp4j#31]
Hi,
Looking for example where xpath selector returns multiple elements - for example a list of links.

Current xpath selector code is basically working on first item returned by $x operator.

How do I use selector to get list of multiple elments - even elements in the form of RemoteObject are fine.

Sample output after hacking selector code

`2017-07-18 14:11:30,381 DEBUG [pool-4-thread-1] io.webfolder.cdp.logger.CdpSlf4jLogger.debug(CdpSlf4jLogger.java:46) - {"method":"Runtime.evaluate","params":{"expression":"$x(\"//input\")","includeCommandLineAPI":true},"id":15}
2017-07-18 14:11:30,382 DEBUG [cpd4j-20] io.webfolder.cdp.logger.CdpSlf4jLogger.debug(CdpSlf4jLogger.java:46) - {"id":15,"result":{"result":{"type":"object","subtype":"array","className":"Array","description":"Array(6)","objectId":"{\"injectedScriptId\":1,\"id\":5}"}}}
`

**Comment by webfolderio** [comment]
Hi @nhrdl 

I add `getObjectIds()` to `Selector` interface. You could use it with xpath or CSS selector to get the list of RemoteObjectId's.
