### ISSUE TITLE
Reconnecting to developer session

### ISSUE THREAD

**Issue by nhrdl** [webfolderio/cdp4j#35]
Chrome developer protocol allows only one client to be connected. CDP4j currently fires TerminateSession which closes the session and corresponding browser window.

Following code allows to reconnect after receiving the termination event. It follows on the same lines as chrome driver and closes any active devtools window and reestablishes session and other code continues as if nothing has happened. I have a wrapper to get session and method looks like following

Apart from following reconnection code, only change is session.close method where I have commented out sesessionFactory.close call.

    public Session getSession() {

		synchronized (this) {
			if (session == null || session.isConnected() == false) {
				if (session != null) {
					String id = null;
					for (final SessionInfo info : sessionFactory.list()) {

						if (info.getUrl().startsWith("chrome-devtools")) {
							sessionFactory.close(info.getId());
						}
					}
					id = session.getId();

					// wait until webSocketDebuggerUrl becomes available, see function DevToolsHttpClient::CloseFrontends from devtools_http_client.cc
					final long checkUntil = System.currentTimeMillis() + TimeUnit.SECONDS.toMillis(120);
					boolean viewStabilzed = false;
					do {
						for (final SessionInfo info : sessionFactory.list()) {
							if (info.getId().equals(id) && !StringUtils.isEmpty(info.getWebSocketDebuggerUrl())) {
								viewStabilzed = true;
								break;
							}
							try {
								Thread.sleep(50);
							} catch (final InterruptedException ignored) {

							}
						}

					} while (System.currentTimeMillis() < checkUntil && !viewStabilzed);
					if (id != null) {
						session = sessionFactory.connect(id);
					}

					session.getCommand().getDOM().getDocument();
				} else {
					session = sessionFactory.create();
				}

				session.getCommand().getNetwork().enable();
				session.getCommand().getDOM().enable();
				session.getCommand().getPage().enable();

				session.addEventListener(this);

			}
			return session;
		}
	}

**Comment by webfolderio** [comment]
Hi @nhrdl 

Chrome developers try's to add [multi-client](https://bugs.chromium.org/p/chromium/issues/detail?id=590878) support to cdp. I don't plan to add multi-client support.

>Apart from following reconnection code, only change is session.close method where I have commented out sesessionFactory.close call.

Could you please let me know the details. I would like to help you to customize your own sesessionFactory.close method.

**Comment by nhrdl** [comment]
I'm not certain, but sessionfactory.close method is actually closing the browser window. From my reconnection perspective this was a big no no. Now when Inspector.detached event is received, it just closes session and not session factory. Session connected flag is set to false - as per original code. I just check the status outside and close another devtools session if needed.

Not clear about you not planning multi client support. Are you saying you won't incorporate this patch or the bug 590878 linked above.

My use case is browser window was getting closed. We don't need to close window on Inspector.detached method as it results in loss of work. Reconnecting the browser on the same lines as chrome driver works fine.

**Comment by webfolderio** [comment]
> Are you saying you won't incorporate this patch or the bug 590878 linked above.

I'm sorry if i my words misunderstood. If you are going to send a pull request i am going to merge it, its ok for me. I mean that i do not have time to implement this feature, if you or anybody wants to contribute, patch requests are welcome.

**Comment by webfolderio** [comment]
Chrome 64 supports multi websocket client.
