### ISSUE TITLE
IncognitoBrowsing sample: .launch(...) first arg should be path/to/chrome

### ISSUE THREAD

**Issue by pfurbacher** [webfolderio/cdp4j#4]
`IncognitoBrowsing.java` thinks it's going to launch Chrome in headless mode, but fails because the first argument to the method is not the path to Chrome. 

`... java.io.IOException: Cannot run program "--headless": ...`

Here's the actual code: 

`SessionFactory factory = new Launcher().launch("--headless", "--disable-gpu");`

It should read 

`SessionFactory factory = new Launcher().launch(pathToChrome, "--headless", "--disable-gpu");`

**Comment by webfolderio** [comment]
Hi @pfurbacher ,

Thanks for the bug report.

With this [commit](https://github.com/webfolderio/cdp4j/commit/238aeb17671f8baabcfc51e14c5d9cdcc3de2fb3) I add `launch(string, string...)` method. Its seems that i broke the api.

I am going to change to launch method with `launch(String, List<String>)` its very bad idea to override launch method with string & variable args.

You might try to use version 1.0.2 which is not broken.

**Comment by webfolderio** [comment]
Fixed by @paine1690
