### ISSUE TITLE
Investigating a Memory Leak with Headless Chrome

### ISSUE THREAD

**Issue by moghtader** [webfolderio/cdp4j#46]
Hi there,

Under a load test on 40 cores, I am trying to create a thread pool of 120 SessionFactory objects on different ports each with 1 headless Session to take screenshots. From my understanding, only an active session can take a screenshot, so many SessionFactory objects would be needed to have truly thread-safe and parallel screenshot capability.

After about 225,000 screenshots, the code appears to start slowing down, and eventually grinds to a halt. After performing some profiling, it appears that there are over 34 million io.webfolder.cdp.internal.gson.internal.LinkedTreeMap$Node objects. Are multiple SessionFactory objects not supported? Let me know if you need any other information. I'd be happy to provide some code for context.

Thanks!
Jake

**Comment by webfolderio** [comment]
> Under a load test on 40 cores, I am trying to create a thread pool of 120 SessionFactory objects on different ports each with 1 headless Session to take screenshots.

Wow, that's too much.

Possible Performance Improvment:

Each SessionFactory create it's own [ThreadPool](https://github.com/webfolderio/cdp4j/blob/master/src/main/java/io/webfolder/cdp/session/SessionFactory.java#L102). You could share the ThreadPool to increase performance. It's not a good idea to create 120 ThreadPool.

> From my understanding, only an active session can take a screenshot,

Unfortunately you need to activate the frame/page before taking the screenshot. This is requirement of Chrome Remote Debugging Protocol. Here is similar issue: https://github.com/cyrus-and/chrome-remote-interface/issues/92

> Are multiple SessionFactory objects not supported?

Multiple SessionFactory supported.

> it appears that there are over 34 million io.webfolder.cdp.internal.gson.internal.LinkedTreeMap$Node objects.

I should fix this memory leak.

**Comment by webfolderio** [comment]
Fixed: https://github.com/webfolderio/cdp4j/commit/98219a41c2463fc665e3c1c8df68a3c5d498921a
