### ISSUE TITLE
How do I turn off the 60 second time limit for the Chrome Headless mode?

### ISSUE THREAD

**Issue by springmarker** [webfolderio/cdp4j#48]
Hi!
    I need to develop something about Chrome Headless. I saw your project some time ago and I thought it was great.
    But there are still some problems with using it, so I decided to develop a lite version myself. But I have some problems. I hope you can help me with this problem. Thank you.
    When I connect to the Chrome with websocket, it works. After 60 seconds, this WebSocket connection will automatically disconnect. When I reconnect, Chrome will lose all of my previous commands.
    When I use your tools, I find your cdp4j doesn't seem to have this problem. But no relevant code was found.

Thanks!

**Comment by webfolderio** [comment]
Hi @springmarker 

Default connection timeout is 60 seconds ([SessionFactory.DEFAULT_CONNECTION_TIMEOUT](https://github.com/webfolderio/cdp4j/blob/master/src/main/java/io/webfolder/cdp/session/SessionFactory.java#L79)).

You should use [SessionFactory(host, port, connectionTimeout, loggerType, threadPool)](https://github.com/webfolderio/cdp4j/blob/master/src/main/java/io/webfolder/cdp/session/SessionFactory.java#L149).
