### ISSUE TITLE
SessionFactory instance in samples should be managed by "try-with-resource"

### ISSUE THREAD

**Issue by pfurbacher** [webfolderio/cdp4j#5]
Consistently, across all the samples, you have 

`SessionFactory factory = new Launcher().launch();`

as the first line of the `main()` method, and 

`factory.close();` 

as the last line.

This "pattern" is flagged with a warning: `Resource 'factory' should be managed by try-with-resource`.

The samples would be improved if you were to fix that warning with: 

```
try (SessionFactory factory = new Launcher().launch()) { 
    ...
}
```

and remove the `factory.close()` statement.

**Comment by webfolderio** [comment]
Thanks for the suggestion. All samples updated and use try-with-resource properly.
