### ISSUE TITLE
'No node with given id found'

### ISSUE THREAD

**Issue by inponomarev** [webfolderio/cdp4j#53]
When working with 6-8 parallel sessions, I'm _sometimes_ getting the following error (during one of navigate/waitdocumentready/getContent):

io.webfolder.cdp.exception.CommandException: No node with given id found
  at io.webfolder.cdp.session.WSAdapter.lambda$onTextMessage$1(WSAdapter.java:122) 

I tried to reproduce this in unit test (10-20 simultaneous sessions in different threads), but it is flaky: sometimes fails, sometimes not. Can this be because of race conditions somewhere in the library, so Chrome session gets wrong node id from neighbour session in another thread? Or is it just Chrome issue? Has somebody seen this before?

**Comment by webfolderio** [comment]
> Chrome session gets wrong node id from neighbour session in another thread?

I don't think so. Each Session object its own WebSocket client and its own state.

Could you please enable debug logging and share with us via support@webfolder.io

Use this logging configuration for debug log:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration packagingData="true">

    <statusListener class="ch.qos.logback.core.status.NopStatusListener" />

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <Pattern>%d{HH:mm:ss.SSS} [%thread] %level %msg%n</Pattern>
        </layout>
    </appender>

    <logger name="cdp4j.session"     level="DEBUG" />
    <logger name="cdp4j.flow"        level="DEBUG" />
    <logger name="cdp4j.factory"     level="DEBUG" />
    <logger name="cdp4j.ws.request"  level="DEBUG" />
    <logger name="cdp4j.ws.response" level="DEBUG" />

    <root level="DEBUG">
        <appender-ref ref="STDOUT" />
    </root>

</configuration>
```

**Comment by inponomarev** [comment]
Done, check the email!

**Comment by webfolderio** [comment]
Thanks for the log. `Selector.releaseObject` release the unused objects. You might get this exception while releasing objects. I am going to make object releasing toggleable.

**Comment by nikhil-bidgely** [comment]
@inponomarev @webfolderio I've also observed this error io.webfolder.cdp.exception.CdpException: Method invoke error: querySelector(#print-report-loaded). Could not find node with given id
when using Session.waitUntil(Predicate, int) in the Predicate implementation:
class WaitPredicate implements Predicate<Session> {

	private final String waitElement;
	private static final Logger logger = LoggerFactory.getLogger(WaitPredicate.class);

	WaitPredicate(String waitElement) {
		this.waitElement = waitElement;
	}

	@Override
	public boolean test(Session s) {
		try {
			return s.matches("#" + waitElement);
		} catch (final CdpException cdpException) {
			logger.error("Exception occured while looking for element {}", waitElement, cdpException);
			return false;
		}
	}
}
it returns this error on s.matches() call.

**Comment by wangay** [comment]
hello.
when would this problem be fixed?

**Comment by wangay** [comment]
@inponomarev have you handled this?

**Comment by inponomarev** [comment]
@wangay No. The only workaround I know is using only one session per browser.

**Comment by wangay** [comment]
@inponomarev  ok

**Comment by wanglong9** [comment]
Do you know the difference between the #62  questions and the second small questions

**Comment by wangay** [comment]
@inponomarev  @wanglong9  
hello. today I have a try with "google Chrome Canary".
and the error never come out again.

=======


alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
#alias google-chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

#chromium 版本
#alias google-chrome="/Applications/Chromium.app/Contents/MacOS/Chromium"
#金丝雀版本
#alias google-chrome="/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary"

**Comment by wangay** [comment]
@webfolderio  So this problem could be shut down..
websocket may get an error when using stablabe chrome version. 
Chrome Canary work well.

**Comment by webfolderio** [comment]
> So this problem could be shut down..

@wangay that's great news.
Could you please share your Chrome & Canary versions?

**Comment by wangay** [comment]
@webfolderio  
chrome:
版本 63.0.3239.132（正式版本） （64 位）

canary:
Version 66.0.3339.0 (Official Build) canary (64-bit)
