### ISSUE TITLE
cdp4j for Android?

### ISSUE THREAD

**Issue by edu-gimenez** [webfolderio/cdp4j#55]
Would it be possible to use cdp4j on Android? Now when you include the jar in an android project ir throw the error:
`Error: com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version> = 26)`

But even if this error was solved, could this library be used to manage Chrome on Android?
Thanks

**Comment by webfolderio** [comment]
Hi,

cdp4j designed and developed for Desktop platforms. I am sorry but we dont plan to support Android.
