### ISSUE TITLE
sessionInfo.getTitle is diff with session.getTitle

### ISSUE THREAD

**Issue by wanglong9** [webfolderio/cdp4j#60]
```
public class SessionInfoTest {

    public static void main(String[] args) throws IOException {
        SessionFactory factory = getSessionFactory(9222);
        Session session = factory.create();
        session.navigate("http://36kr.com/p/5037279.html");
        session.waitDocumentReady();
        List<SessionInfo> list = getPageSessionInfo(factory);
        for (SessionInfo info : list) {
            String id = info.getId();
            System.out.println(info.getTitle());
            System.out.println(factory.connect(id).getTitle());
        }
        session.close();
        factory.close();
    }

    private static SessionFactory getSessionFactory(int port) {
        Launcher launcher = new Launcher(getFreePort(DEFAULT_PORT));
        Path remoteProfileData = get(getProperty("java.io.tmpdir")).resolve("remote-profile-" + new Random().nextInt());
        SessionFactory factory = launcher.launch(asList("--user-data-dir=" + remoteProfileData.toString()));
        return factory;
    }

    protected static int getFreePort(int portNumber) {
        try (ServerSocket socket = new ServerSocket(portNumber)) {
            int freePort = socket.getLocalPort();
            return freePort;
        } catch (IOException e) {
            return getFreePort(portNumber + 1);
        }
    }

    public static List<SessionInfo> getPageSessionInfo(SessionFactory factory) {
        List<SessionInfo> list = new ArrayList<>();
        for (SessionInfo info : factory.list()) {
            if (info.getType().equals("page")) {
                list.add(info);
            }
        }
        return list;
    }

}
```

跟链家合体的盛世管家其实悄悄剥离了租赁业务&quot;爱上租&quot;_36氪
跟链家合体的盛世管家其实悄悄剥离了租赁业务"爱上租"_36氪

**Comment by wanglong9** [comment]
public class Test {
    public static void main(String[] args) throws IOException {
        SessionFactory factory1 = getSessionFactory(9222);
        List<SessionInfo> list = factory1.list();
        Session session = factory1.create();
        session.navigate("http://www.baidu.com");
        session.waitDocumentReady();
        for (SessionInfo info: list) {
            String id = info.getId();
            System.out.println(info.getTitle());
            System.out.println(factory1.connect(id).getTitle());
        }
        session.close();
        factory1.close();
    }

    private static SessionFactory getSessionFactory(int port) {
        Launcher launcher = new Launcher(port);
        return launcher.launch();
    }
}

``Connected to the target VM, address: '127.0.0.1:65111', transport: 'socket' ``
``新标签页``
``百度一下，你就知道``


It is confusing

**Comment by wanglong9** [comment]
the SessionInfo title show \&quot;
the Session title show \"

**Comment by webfolderio** [comment]
@wanglong9 thanks for the helpful information.
