### ISSUE TITLE
support for java 8 VS java.lang.ProcessHandle.of imports

### ISSUE THREAD

**Issue by prakapenka** [webfolderio/cdp4j#61]
In master branch - 
```java
import static java.lang.ProcessHandle.of;

import java.lang.ProcessHandle.Info;

public class DefaultProcessManager extends ProcessManager {
```

has imports of ProcessHandle which is introduced in java 9. That means master will not compile on java 8 any more.
Is it possible to handle processes with java 8 functionality?

Thank you in advance.

**Comment by webfolderio** [comment]
Hi @prakapenka 

Yes, that's true that cdp4j compiled with Java 9 with source level 8.

`AdaptiveProcessManager` and `DefaultProcessManager` requires Java 9. You should delete these files before compiling cdp4j with Java 8.

> Is it possible to handle processes with java 8 functionality?

Yes, `WindowsProcessManager` and `LinuxProcessManager` is compatible with Java 8 and `AdaptiveProcessManager` and `DefaultProcessManager` is compatible with Java 9.
