### ISSUE TITLE
some question with headless 

### ISSUE THREAD

**Issue by wanglong9** [webfolderio/cdp4j#62]
1 、 when i create headlessSession like this 
` factory = launcher.launch(asList("--disable-gpu", "--headless"));`
it doesn't work  sometime without any log.

2、after i read [Attributes.java](https://github.com/webfolderio/cdp4j/blob/master/src/test/java/io/webfolder/cdp/sample/Attributes.java) and [PrintToPDF.java](https://github.com/webfolderio/cdp4j/blob/master/src/test/java/io/webfolder/cdp/sample/PrintToPDF.java)
What's the difference between 
 
```
factory = launcher.launch(asList("--disable-gpu", "--headless"));
Session session = factory.create();
```
and
```
SessionFactory factory = launcher.launch(asList("--disable-gpu", "--headless"))
String context = factory.createBrowserContext();
Session session = factory.create(context)
```

**Comment by 2788** [comment]
i think there is no difference between  asList("--disable-gpu", "--headless") and asList("--disable-gpu", "--headless")  beacause  they both are used in the command  "chrome --headless --disable-gpu" or "chrome --disable --heardess". 
so i think they are identical.  

when i use headless  i need winp on windows.  You can try it .

Finally, 说英语好累啊

**Comment by wanglong9** [comment]
@2788 谢谢，
其实我想问的
`Session session = factory.create();`
和
```
String context = factory.createBrowserContext();
Session session = factory.create(context)
```
的区别。
还有winp是什么东西？

**Comment by 2788** [comment]
Session session = factory.create(); 这个是直接创建一个tab
String context = factory.createBrowserContext();
Session session = factory.create(context) 这个是创建一个上下文然后再创建一个tab  这样这个tab是有自己的cookie，session了，如果每个tab都创建了 上下文 你可以认为他们都是独立的，session cookie 不会共享

**Comment by wanglong9** [comment]
@2788 学习了，谢谢
