### ISSUE TITLE
Launcher.kill doesn't work 

### ISSUE THREAD

**Issue by dobsov** [webfolderio/cdp4j#65]
because call stub method NullProcessManager.kill

**Comment by prakapenka** [comment]
because we need to set to Laucher ProcessManager explicitly.
Even I would rather happy to set there my own implementation but blocked by this issue: 
https://github.com/webfolderio/cdp4j/issues/66

**Comment by webfolderio** [comment]
Here is a sample usage:

If your Java version is Java 9:

```java
        Launcher launcher = new Launcher();
        launcher.setProcessManager(new AdaptiveProcessManager());

        try (SessionFactory factory = launcher.launch();
                            Session session = factory.create()) {
        }

        launcher.kill();
```
If your Java version is Java 8:

```java
launcher.setProcessManager(new LinuxProcessManager());
launcher.setProcessManager(new WindowsProcessManager());
```
