### ISSUE TITLE
Version 2.1.6 is not available on Maven Central

### ISSUE THREAD

**Issue by jgesser** [webfolderio/cdp4j#68]
The latest version (2.1.6) is not yet available on Maven Central Repository.
It would be great to have the latest changes available via maven dependency.

**Comment by webfolderio** [comment]
Version [2.2.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/io/webfolder/cdp4j/2.2.0-SNAPSHOT/) is released to maven central.
