### ISSUE TITLE
the limitation of sessions

### ISSUE THREAD

**Issue by 2788** [webfolderio/cdp4j#70]
I create 50 threads  which each other create one session to do someting , the program work fine most of time.

But  when there are more than 50 threads, the thread throw socket connect fail.  Is there a solution ?

**Comment by webfolderio** [comment]
Hi,

Neither cdp4j nor Chrome  limits number of connection. Did you run cdp4j and chrome on the same host?

**Comment by 2788** [comment]
yes, i use the same sessionfactory
