### ISSUE TITLE
Support for parameters headerTemplate and footerTemplate in Page.printToPDF

### ISSUE THREAD

**Issue by dlevis** [webfolderio/cdp4j#71]
Support for the `headerTemplate` and `footerTemplate` parameters when printing to PDF has been [recently added](https://github.com/GoogleChrome/puppeteer/pull/1625) in Chrome DevTools Protocol. It would be great to add support for that in cdp4j.

**Comment by webfolderio** [comment]
hi @dlevis did you try to use [Page.printToPDF](https://github.com/webfolderio/cdp4j/blob/master/src/main/java/io/webfolder/cdp/command/Page.java#L251) method. `headerTemplate `and `footerTemplate`  parameters should work.

**Comment by dlevis** [comment]
Oh I see, great. Since the javadoc was not updated I thought it was not implemented yet. Thanks!

Do you plan to do an official release soon?

**Comment by webfolderio** [comment]
You could use snapshot version from maven central. Version 2.2.0 probably will be released next month.

```xml
<dependency>
    <groupId>io.webfolder</groupId>
    <artifactId>cdp4j</artifactId>
    <version>2.2.0-SNAPSHOT</version>
</dependency>
```

**Comment by dlevis** [comment]
The snapshot version does not seem to be available in Maven Central:

`Could not resolve: io.webfolder:cdp4j:2.2.0-SNAPSHOT`

I will wait for the next release. Thanks.

**Comment by webfolderio** [comment]
jar: https://oss.sonatype.org/content/repositories/snapshots/io/webfolder/cdp4j/2.2.0-SNAPSHOT/cdp4j-2.2.0-20180106.080408-1.jar

source: https://oss.sonatype.org/content/repositories/snapshots/io/webfolder/cdp4j/2.2.0-SNAPSHOT/cdp4j-2.2.0-20180106.080408-1-sources.jar

Do not forgot to configure maven for snapshot repository: https://stackoverflow.com/questions/7713996/is-there-a-way-to-make-maven-download-snapshot-versions-automatically
