### ISSUE TITLE
Inclusion of cdp4j dependency breaks JDK 9 maven compilation

### ISSUE THREAD

**Issue by jhorowitz-firedrum** [webfolderio/cdp4j#75]
Due to a JDK 9 compiler bug, any project that depends on cdp4j cannot build using mvn compile using Java 9.

Ultimately, the error has to do with invalid modified dates stored in the resulting jar distribution.
This has been fixed upstream; upgrading to reproducible-build-maven-plugin v0.4 would fix the issue.

Please refer to the upstream issue for details: https://github.com/Zlika/reproducible-build-maven-plugin/issues/12

**Comment by webfolderio** [comment]
Thanks for the bug report.

Please update your cdp4j version to 2.2.1

**Comment by jhorowitz-firedrum** [comment]
Thanks! That fixes it :)
