### ISSUE TITLE
using setDownloadBehavior in java 

### ISSUE THREAD

**Issue by jwingo1015** [webfolderio/cdp4j#79]
I cant seem to find any examples of using setDownloadBehavior in java. Is there any example

**Comment by webfolderio** [comment]
https://github.com/webfolderio/cdp4j/blob/master/src/test/java/io/webfolder/cdp/sample/DownloadFile.java

**Comment by jwingo1015** [comment]
yeah but im not using session to launch the page im using selenium

**Comment by webfolderio** [comment]
Hi @jwingo1015 unfortunately i am not familar with selenium.

**Comment by jwingo1015** [comment]
System.setProperty("webdriver.chrome.driver", "/path/chromedriver");

        // Add options to Google Chrome. The window-size is important for responsive sites
        ChromeOptions options = new ChromeOptions();
        options.setBinary("/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary");
        options.addArguments("--headless");
        options.addArguments("window-size=1200x1200");

        String downloadFilepath = "./Downloads/";
        HashMap<String, Object> chromePrefs = new HashMap<>();
        chromePrefs.put("browser.setDownloadBehavior", "allow");
        chromePrefs.put("profile.default_content_settings.popups", 0);
        chromePrefs.put("download.default_directory", downloadFilepath);

        options.setExperimentalOption("prefs", chromePrefs);
        WebDriver driver = new ChromeDriver(options);

        driver.get("https://website/login");

**Comment by jwingo1015** [comment]
but the browser.setDownloadBehavior doesn't work for me
