### ISSUE TITLE
WSContext configurable timeout

### ISSUE THREAD

**Issue by wrightm** [webfolderio/cdp4j#87]
Hi,

I am running into an issue with the ```printToPDF``` taking more than 10 seconds. This is a problem due to the ```WSContext``` only allowing connections to last 10 seconds before throwing an ```InterruptedException```

Ideally this would be configurable. Maybe taking the ```SessionFactory``` ```connectionTimeout```. I am happy to put up a PR if others think this is a good idea?

**Comment by wrightm** [comment]
https://github.com/webfolderio/cdp4j/pull/88

**Comment by webfolderio** [comment]
Thanks for the pull request. 2.2.5-SNAPSHOT version is released and ready to use.

**Comment by wrightm** [comment]
@webfolderio is there a plan to release 2.2.5 anytime soon?

**Comment by webfolderio** [comment]
setConnectionTimeout renamed to Session.setWebSocketReadTimeout()
