### ISSUE TITLE
Error creating shaded jar: null

### ISSUE THREAD

**Issue by hajderr** [webfolderio/cdp4j#89]
`$> mvn install`

`ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade (default) on project cdp4j: Error creating shaded jar: null: IllegalArgumentException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

mvn 3.5.0 with Java 9

**Comment by webfolderio** [comment]
Could you please try to execute mvn `-DskipTests install`
