### ISSUE TITLE
How can i pass credentatials for printToPDF ? 

### ISSUE THREAD

**Issue by gandhi-jay** [webfolderio/cdp4j#9]
I have a page which requires basic authentication. How do i pass username and password when cdp4j makes request to given page?

**Comment by webfolderio** [comment]
hi @gandhi-jay You could credentials within http url.

Sample basic auth url:

https://user:passwd@httpbin.org/basic-auth/user/passwd

**Comment by gandhi-jay** [comment]
hey, @webfolderio 
Support for embedded creds in url is dropped and it will be handled as network error.
check this - [feature](https://www.chromestatus.com/feature/5669008342777856)

**Comment by gandhi-jay** [comment]
@webfolderio Just figured it out. You can pass creds as ExtraHTTPHeaders.

```
                String userCredentials = "<username>:<password>";
            	String basicAuth = "Basic " + new String(Base64.getEncoder().encode(userCredentials.getBytes()));
            	Map<String,Object> map = new HashMap<String,Object>();  
            	map.put("Authorization", basicAuth);
            	session.getCommand().getNetwork().setExtraHTTPHeaders(map);
                session.navigate("<url>");
```

**Comment by webfolderio** [comment]
@gandhi-jay Thank you for your contribution.

I add a [sample](https://github.com/webfolderio/cdp4j/blob/master/src/test/java/io/webfolder/cdp/sample/BasicAuthentication.java) for basic authentication based on your code snippet.
