### ISSUE TITLE
Release 2.2.5

### ISSUE THREAD

**Issue by wrightm** [webfolderio/cdp4j#90]
Hi,

I am needing to use the changes put in 2.2.5-SNAPSHOT in my project. Is there a release planned? If you are needing help to make a release I am more than happy to help.

**Comment by webfolderio** [comment]
2.2.5-SNAPSHOT is released.

https://oss.sonatype.org/content/repositories/snapshots/io/webfolder/cdp4j/2.2.5-SNAPSHOT/
