### ISSUE TITLE
Support passing arguments to Session captureScreenshot

### ISSUE THREAD

**Issue by akawalsky** [webfolderio/cdp4j#97]
For my application, I want to be able to take a screenshot of only a certain portion of the page. The library does not currently have a great interface for this, despite the fact that Page supports it.

Workaround right now involves doing something along the lines of
```
Viewport viewport = new Viewport();
viewport.setX(0.0);
viewport.setY(0.0);
viewport.setWidth(100.0);
viewport.setHeight(100.0);
viewport.setScale(2.0);
Page page = session.getCommand().getPage();
page.captureScreenshot(ImageFormat.Png, (Integer)null, viewport, true);
````
which feels like a hack.

I propose adding an overridden method 
```
captureScreenshot(@Optional ImageFormat format, @Optional Integer quality,
                                    @Optional Viewport clip, @Experimental @Optional Boolean fromSurface)
```
to the Session class.

**Comment by webfolderio** [comment]
Hi, @akawalsky 
Thanks for the pull request.
