### ISSUE TITLE
io.webfolder.cdp.exception.CdpException: Unable to create target

### ISSUE THREAD

**Issue by w25193** [webfolderio/cdp4j#99]
`    public static void main(String args[]){
        ArrayList<String> command = new ArrayList<String>();

        command.add("--headless");
        Launcher launcher = new Launcher();
        SessionFactory factory = launcher.launch(command);

        Session session = null;
        session = factory.create();
        session.navigate("https://www.google.com/");
        session.wait(10);
        String content = session.getContent();
        System.out.println(content);
    }`
Only the first operation is normal, and the second run is wrong.

**Comment by webfolderio** [comment]
Hi @w25193 

Could you please share the full sample code instead of code snippet.

**Comment by w25193** [comment]
![image](https://user-images.githubusercontent.com/29299286/41264315-9d1e2daa-6e1e-11e8-84c1-bc4cd95fd894.png)
that`s all  0.0

**Comment by w25193** [comment]
hi @webfolderio I think I find out where the problem is. The two processes are not turned off. But what method should I use to turn them off
launcher.getProcessManager().kill() this method doesn`t work
![image](https://user-images.githubusercontent.com/29299286/41268338-2564300c-6e32-11e8-9b7b-230a3ed01de1.png)
![image](https://user-images.githubusercontent.com/29299286/41268339-258069fc-6e32-11e8-8695-591c4b772f8b.png)

**Comment by webfolderio** [comment]
@w25193 

You should set the ProcessManager. Default one is NullProcessManager which does not kill the process.

Here is a working sample:

```java
Launcher launcher = new Launcher();
launcher.setProcessManager(new AdaptiveProcessManager());

```

**Comment by w25193** [comment]
@webfolderio 
it throw a new exception 
![image](https://user-images.githubusercontent.com/29299286/41274613-9b9265f0-6e50-11e8-8230-8ae5f50c1ddd.png)
![image](https://user-images.githubusercontent.com/29299286/41274620-9ede561a-6e50-11e8-83fb-38727277f596.png)

**Comment by w25193** [comment]
sorry it works - -!
